# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FootBaller',
            new_name='FootBallPlayer',
        ),
    ]
