# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0002_auto_20170416_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballplayer',
            name='age',
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
