# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0003_auto_20170416_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballplayer',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='birth_date',
            field=models.DateTimeField(default=None),
        ),
    ]
